[ADD] Cgu page to dev
WanderAR-app/AppFront pull request #3
Opened 2023-05-30 08:46 UTC by rox51124

2023-05-30 16:21 UTC, CyrilDehaese requested changes
c'est propre dans l'ensemble deux trois petites perfections à faire

2023-05-30 16:21 UTC, CyrilDehaese commented on App.tsx
> -export default function App() {
pourquoi tu retire cet export et tu le met à la fin ?

2023-05-30 16:21 UTC, CyrilDehaese commented on src/CguPage.tsx
> +  };
faut voir soit a faire un call à la db pour dire que cet user accepte puis le redirect sur home ou fermer l'app

on fera le call db quand ce sera dispo niveau serveur mais tu peux deja faire le close de l'app et le redirect

2023-05-30 16:21 UTC, CyrilDehaese commented on src/CguPage.tsx
> +        <Image source={require('../assets/WanderAR.png')} style={styles.logo} />
met une variable c'est plus propre

2023-05-30 16:21 UTC, CyrilDehaese commented on src/CguPage.tsx
> +const { width, height } = Dimensions.get('window');
change le nom de width et height pour qu'on sache que tu parle de la taille de l'écran et pas d'un autre

2023-05-30 16:21 UTC, CyrilDehaese commented on src/CguPage.tsx
> +    shadowColor: "#D1D9E6",
je ferais des couleurs avec des noms pour que ce soit plus simple que de copier l'hexa à chaque fois

2023-06-04 15:36 UTC, rox51124 commented on src/CguPage.tsx
> +const { width, height } = Dimensions.get('window');
modification fait

2023-06-04 15:36 UTC, rox51124 commented on src/CguPage.tsx
> +  };
modification fait

2023-06-04 15:38 UTC, rox51124 commented on src/CguPage.tsx
> +    shadowColor: "#D1D9E6",
on peut valider la pull request et faire la modification apres ?

2023-06-04 15:38 UTC, rox51124 commented on App.tsx
> -export default function App() {
je sais plus, c'est important ?

2023-06-05 11:37 UTC, CyrilDehaese commented on App.tsx
> -export default function App() {
non juste faut faire attention à ce que tout soit uniforme

2023-06-05 11:38 UTC, CyrilDehaese commented on src/CguPage.tsx
> +    shadowColor: "#D1D9E6",
oui pas de soucis

2023-06-05 11:38 UTC, CyrilDehaese approved these changes

2023-06-05 11:40 UTC, merged